[features]
seeds = false
skip-lint = false
[programs.devnet]
helloworm = "FCfcutChmLTZjb7gKpfBqwPSdxi4NCs71bnVqiMuY9dp"
hello_world = "AojD1yubXcLNTBgXLbHCJV3GMeZk3TjpdiHWd8JbgtmN"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/katherinee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
